# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Daily Check In Task

on:
  # Allow manual start
  workflow_dispatch:
  # Run job on 16:15UTC/00:15CST daily
  schedule:
  - cron: "15 16 * * *"
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make Gradle wrapper executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build test
      env:
        USER_1_ID: ${{ secrets.KISSNAVELHK_TOKEN_ID }}
        USER_1_TOKEN: ${{ secrets.KISSNAVELHK_TOKEN }}
        USER_2_ID: ${{ secrets.LAWQZYZ_TOKEN_ID }}
        USER_2_TOKEN: ${{ secrets.LAWQZYZ_TOKEN }}
